### ISSUE TITLE
CDN error

### ISSUE THREAD

**Issue by thijsvgils** [thenikhilk/sharepoint-instagram-feed#3]
First of all, great work! 

My issue: I'm able to add the app to the app catalog, but when adding the webpart to the page I get the following error:

> [SPLoaderError.loadComponentError]:
> Failed to load component "ed33f1de-aa1c-4e68-bb4e-bc4835f865ea" (InstagramFeedWebPart). Original error: Failed to load URL 'https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/s-instagramfeedwebpartstrings_en-us_4e9dfa86b94ddc3714c06cec6512bffe.js' for resource 'InstagramFeedWebPartStrings' in component 'ed33f1de-aa1c-4e68-bb4e-bc4835f865ea' (InstagramFeedWebPart). The file was not found in the server.

How do I ensure the CDN repo is accessible to SharePoint? I'm guessing that's the problem...

Thanks in advance!

**Comment by thenikhilk** [comment]
Hello @thijsvgils 

Thank you for using the web part, error that you are getting, I'm not sure why since the actual URL for this file should be [https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/sharepoint-instagram-feed-instagramfeedwebpartstrings_en-us_134e1dc2c69cdff4287a269a350b053b.js](https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/sharepoint-instagram-feed-instagramfeedwebpartstrings_en-us_134e1dc2c69cdff4287a269a350b053b.js)

But given your site is loading another URL which may be a n issue for other users I've added the same file with the name at the CDN and now your URL should resolve within the WebPart

https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/s-instagramfeedwebpartstrings_en-us_4e9dfa86b94ddc3714c06cec6512bffe.js

Do let me know if the issue was solved or you need any other assistance

CDN Stats don't show the file being requested:
![CDN Stats](https://user-images.githubusercontent.com/5794800/68380472-edc2f600-0175-11ea-97bd-5b743b7fe1d5.png)

**Comment by nschahrochie** [comment]
Hi - i have the same issue, now after your changes i get a new error:
"An error occurred - Failed to load data, please check WebPart settings or try again later"

<img width="904" alt="Bildschirmfoto 2019-11-07 um 11 28 10" src="https://user-images.githubusercontent.com/17612292/68381332-c65a3200-0151-11ea-96ed-a829c9cd4acc.png">

**Comment by nschahrochie** [comment]
I havent got any near the setting to add the username yet... The error occurs when i add the webpart. 
insta name: maxmustermann893

**Comment by thenikhilk** [comment]
Nope, only public profiles are supported. I saw there are no posts on your account try adding a sample post it should work

The error that you are seeing shows up when there is nothing to render or malformed data.

For the issue reported by @thijsvgils I just check installing it on a fresh tenant and using it, it seems to work:
![image](https://user-images.githubusercontent.com/5794800/68382598-1351fe80-017a-11ea-82c1-82b6ff506ed2.png)

**Comment by thenikhilk** [comment]
@nschah I see that you've added posts and now your profile seems to be rendering in my testing:
![image](https://user-images.githubusercontent.com/5794800/68382781-6cba2d80-017a-11ea-986d-09fd3a1806ed.png)

**Comment by nschah** [comment]
how is that possible! i still receive the error, and i have tried with other public profiles aswell. it shows the same error :(
<img width="839" alt="Bildschirmfoto 2019-11-07 um 11 51 54" src="https://user-images.githubusercontent.com/17612292/68383085-3e762700-0155-11ea-891a-7212be871be0.png">

**Comment by thenikhilk** [comment]
this is a separate issue, not the original one, please log a new issue for this and provide me a screenshot of the console and your network requests from the developer console(press f12 to open) for any failed requests

Console:
![image](https://user-images.githubusercontent.com/5794800/68383216-41840e00-017b-11ea-8f78-8ec0ce868252.png)

Network:
![image](https://user-images.githubusercontent.com/5794800/68383262-5496de00-017b-11ea-9922-d3203a54cf19.png)

**Comment by nschah** [comment]
I dont know how but the Issue is resolved after pressing F12
Thank you so much for the help!
<img width="1263" alt="Bildschirmfoto 2019-11-07 um 12 00 38" src="https://user-images.githubusercontent.com/17612292/68383622-4a161d80-0156-11ea-947f-8fc24f82614a.png">

**Comment by thijsvgils** [comment]
> Hello @thijsvgils
> 
> Thank you for using the web part, error that you are getting, I'm not sure why since the actual URL for this file should be https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/sharepoint-instagram-feed-instagramfeedwebpartstrings_en-us_134e1dc2c69cdff4287a269a350b053b.js
> 
> But given your site is loading another URL which may be a n issue for other users I've added the same file with the name at the CDN and now your URL should resolve within the WebPart
> 
> https://cdn.jsdelivr.net/gh/thenikhilk/cdn/tnk-sp-ig/s-instagramfeedwebpartstrings_en-us_4e9dfa86b94ddc3714c06cec6512bffe.js
> 
> Do let me know if the issue was solved or you need any other assistance also make sure you make it available to the tenant while deploying(tick the checkbox shown in the image below):
> ![image](https://user-images.githubusercontent.com/5794800/68382913-a854f780-017a-11ea-8b6c-e5d5d2600b73.png)
> 
> CDN Stats don't show the file being requested:
> ![CDN Stats](https://user-images.githubusercontent.com/5794800/68380472-edc2f600-0175-11ea-97bd-5b743b7fe1d5.png)

Thanks for that! I'm now able to add the webpart, and enter an Instagram account name, but receiving the same error as @nschah 
![image](https://user-images.githubusercontent.com/34765064/68385098-58b20400-0159-11ea-8df1-a32f8169a1f2.png)

**Comment by thenikhilk** [comment]
This error tracked in #4
